FROM ubuntu:jammy

# Update packages
RUN apt-get update
RUN apt-get upgrade -y

# Install dev packages
RUN apt-get install -y cmake
RUN apt-get install -y python3
RUN apt-get install -y gdb
RUN apt-get install -y git
RUN apt-get install -y g++
